.TH "com.zeuslearning.automation.io.LogToExternalFile" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.io.LogToExternalFile \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogToExternalFile\fP (String filePath)"
.br
.ti -1c
.RI "void \fBinfo\fP (String information)"
.br
.ti -1c
.RI "void \fBwarn\fP (String warning)"
.br
.ti -1c
.RI "void \fBerror\fP (String error)"
.br
.ti -1c
.RI "void \fBcloseAll\fP ()"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "void \fBappend\fP (String message)"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "File \fBlogFile\fP"
.br
.ti -1c
.RI "PrintWriter \fBwriter\fP"
.br
.ti -1c
.RI "SimpleDateFormat \fBsdf\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fB_filePath\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
