.TH "com.zeuslearning.automation.unittests.ValuePair" 3 "Mon Mar 20 2017" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.unittests.ValuePair \- 
.SH SYNOPSIS
.br
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fBname\fP"
.br
.ti -1c
.RI "String \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
