.TH "com.zeuslearning.automation.io.IInputOutputOps" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.io.IInputOutputOps \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcom\&.zeuslearning\&.automation\&.io\&.BasicFileOps\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBclose\fP ()"
.br
.ti -1c
.RI "boolean \fBopen\fP (Object source)  throws IOException"
.br
.ti -1c
.RI "boolean \fBopen\fP (String source)"
.br
.ti -1c
.RI "Object \fBread\fP ()"
.br
.ti -1c
.RI "Object \fBreadAll\fP ()"
.br
.ti -1c
.RI "boolean \fBreset\fP ()"
.br
.ti -1c
.RI "boolean \fBwrite\fP (Object data)"
.br
.ti -1c
.RI "boolean \fBwrite\fP (String data)"
.br
.ti -1c
.RI "String \fBcreatePath\fP (String relativePath)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
