.TH "com.zeuslearning.automation.selenium.interactions.HtmlAlertOps" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.selenium.interactions.HtmlAlertOps \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.zeuslearning\&.automation\&.interactions\&.IAlertOperations\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHtmlAlertOps\fP (Object driver)"
.br
.ti -1c
.RI "boolean \fBdismissAlert\fP ()"
.br
.ti -1c
.RI "boolean \fBacceptAlert\fP ()"
.br
.ti -1c
.RI "String \fBgetAlertText\fP ()"
.br
.ti -1c
.RI "boolean \fBsendPromptText\fP (String text)"
.br
.ti -1c
.RI "Object \fBswitchToAlert\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "WebDriver \fB_driver\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.HtmlAlertOps\&.acceptAlert ()\fC [inline]\fP"
Accept the alerts / Click the \fCYes\fP or \fCOK\fP button\&.
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if accept operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IAlertOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.HtmlAlertOps\&.dismissAlert ()\fC [inline]\fP"
Dismiss the alerts / Click the \fCCancel\fP button\&.
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if dismiss operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IAlertOperations\fP\&.
.SS "String com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.HtmlAlertOps\&.getAlertText ()\fC [inline]\fP"
Return text string on the alert popup\&.
.PP
\fBReturns:\fP
.RS 4
{String} - returns text string on the alert popup\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IAlertOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.HtmlAlertOps\&.sendPromptText (String text)\fC [inline]\fP"
Send a prompt text to the alert popup\&.
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if prompt operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IAlertOperations\fP\&.
.SS "Object com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.HtmlAlertOps\&.switchToAlert ()\fC [inline]\fP"
Accept the alerts / Click the \fCYes\fP or \fCOK\fP button\&.
.PP
\fBReturns:\fP
.RS 4
{Object} - returns an \fCAlert\fP object if alert is found, else returns a \fCNull\fP object\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IAlertOperations\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
