.TH "com.zeuslearning.automation.unittests.TestSikuli" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.unittests.TestSikuli \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)  throws FindFailed, InterruptedException, GeneralSecurityException,             IOException, ServiceException, URISyntaxException "
.br
.ti -1c
.RI "static void \fBclickScreen\fP (String element)  throws FindFailed "
.br
.ti -1c
.RI "static void \fBtypeTextOnScreen\fP (String element, String text)  throws FindFailed "
.br
.ti -1c
.RI "static void \fBaddNewConnection\fP ()  throws FindFailed "
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static Screen \fBscreen\fP = new Screen()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
