.TH "com.zeuslearning.automation.selenium.interactions.Mouse" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.selenium.interactions.Mouse \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMouse\fP (Object driver)"
.br
.ti -1c
.RI "boolean \fBclick\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBclick\fP (Object locator, boolean ctrlKey, boolean altKey, boolean shiftKey, boolean metaKey)"
.br
.ti -1c
.RI "boolean \fBclickAllElementsLocatedBy\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBclickUsingOffset\fP (Object locator, int x, int y)"
.br
.ti -1c
.RI "boolean \fBclickWithoutScrolling\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBcontextClick\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBcontextClickUsingCode\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBcontextClickUsingOffset\fP (Object locator, int x, int y)"
.br
.ti -1c
.RI "boolean \fBcontextClickWithoutScrolling\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBdoubleClick\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBdoubleClickUsingCode\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBdoubleClickUsingCodeWithTwoClicks\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBdoubleClickUsingOffset\fP (Object locator, int x, int y)"
.br
.ti -1c
.RI "boolean \fBdoubleClickWithoutScrolling\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBdragdropUsingMouse\fP (Object locator, int offsetX1, int offsetY1, int width, int height)"
.br
.ti -1c
.RI "boolean \fBlistClick\fP (Object locator, int index)"
.br
.ti -1c
.RI "boolean \fBmouseDown\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBmouseDown\fP (Object locator, int x, int y)"
.br
.ti -1c
.RI "boolean \fBmouseMove\fP (Object locator, int x, int y)"
.br
.ti -1c
.RI "Object \fBmouseOver\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBmouseUp\fP (Object locator)"
.br
.ti -1c
.RI "boolean \fBmouseUp\fP (Object locator, int x, int y)"
.br
.ti -1c
.RI "boolean \fBscroll\fP (int xVal, int yVal)"
.br
.ti -1c
.RI "boolean \fBscroll\fP (Object elementValue)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBclick\fP (WebElement elementValue)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "WebDriver \fB_driver\fP"
.br
.ti -1c
.RI "\fBIExecuteJavascript\fP \fB_js\fP"
.br
.ti -1c
.RI "int \fB_attempts\fP"
.br
.ti -1c
.RI "\fBQueryHtml\fP \fB_query\fP"
.br
.ti -1c
.RI "Actions \fB_action\fP"
.br
.ti -1c
.RI "\fBTimeout\fP \fB_timeout\fP"
.br
.ti -1c
.RI "String \fB_script\fP"
.br
.ti -1c
.RI "WebElement \fB_element\fP"
.br
.ti -1c
.RI "\fBIWindowOperations\fP \fB_browser\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.click (Object locator)\fC [inline]\fP"
Performs a click operation on the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element to be clicked\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.click (Object locator, boolean ctrlKey, boolean altKey, boolean shiftKey, boolean metaKey)\fC [inline]\fP"
Performs a click operation on the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.br
\fIctrlKey\fP {boolean} - Press control key if \fCtrue\fP 
.br
\fIaltKey\fP {boolean} - Press alt key if \fCtrue\fP 
.br
\fIshiftKey\fP {boolean} - Press shift key if \fCtrue\fP 
.br
\fImetaKey\fP {boolean} - Press meta key if \fCtrue\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.clickAllElementsLocatedBy (Object locator)\fC [inline]\fP"
Performs a click operation on all the element located by the path specified by \fClocator\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.clickUsingOffset (Object locator, int x, int y)\fC [inline]\fP"
Performs a click on an element at x and y\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.br
\fIx\fP {int} - Offset along the X-Axis w\&.r\&.t\&. element\&. 
.br
\fIy\fP {int} - Offset along the Y-Axis w\&.r\&.t\&. element\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.clickWithoutScrolling (Object locator)\fC [inline]\fP"
Performs a click on the specified element without scrolling it
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.contextClick (Object locator)\fC [inline]\fP"
Performs a context click on the specified element
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if context click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.contextClickUsingOffset (Object locator, int x, int y)\fC [inline]\fP"
Performs a context click on an element at x and y\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.br
\fIx\fP {int} - Offset along the X-Axis w\&.r\&.t\&. element\&. 
.br
\fIy\fP {int} - Offset along the Y-Axis w\&.r\&.t\&. element\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.contextClickWithoutScrolling (Object locator)\fC [inline]\fP"
Performs a context click on the specified element without scrolling it
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if context click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.doubleClick (Object locator)\fC [inline]\fP"
Performs a double-click operation on the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element to be double-clicked\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if double-click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.doubleClickUsingCode (Object locator)\fC [inline]\fP"
Performs a double-click operation on the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element to be double-clicked\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if double-click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.doubleClickUsingCodeWithTwoClicks (Object locator)\fC [inline]\fP"
Performs a double-click operation on the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element to be double-clicked\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if double-click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.doubleClickUsingOffset (Object locator, int x, int y)\fC [inline]\fP"
Performs a double click on an element at x and y\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.br
\fIx\fP {int} - Offset along the X-Axis w\&.r\&.t\&. element\&. 
.br
\fIy\fP {int} - Offset along the Y-Axis w\&.r\&.t\&. element\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.doubleClickWithoutScrolling (Object locator)\fC [inline]\fP"
Performs a double-click operation on the element without scrolling it\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element to be double-clicked\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if double-click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.dragdropUsingMouse (Object locator, int offsetX1, int offsetY1, int offsetX2, int offsetY2)\fC [inline]\fP"
Drag inside an element from one position\fCoffsetX1\fP along the X-Axis and by \fCoffsetY1\fP along the Y-Axis and move to \fCoffsetX2\fP along the X-Axis and to \fCoffsetY2\fP along the Y-Axis and drop\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Drag inside an Element present at the \fClocator\fP\&. 
.br
\fIoffsetX1\fP {int} - start position along the X-Axis\&. 
.br
\fIoffsetY1\fP {int} - start position along the Y-Axis\&. 
.br
\fIoffsetX2\fP {int} - end position along the X-Axis\&. 
.br
\fIoffsetY2\fP {int} - end position along the Y-Axis\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if drag operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.listClick (Object locator, int index)\fC [inline]\fP"
Clicks on the element found using findElements\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the elements\&. 
.br
\fIindex\fP {int} - index number of the element to be clicked\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if click operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.mouseDown (Object locator)\fC [inline]\fP"
Trigger mouse down event on the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - Returns \fCtrue\fP if mouse over was successful, else \fCfalse\fP\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.mouseDown (Object locator, int xOffset, int yOffset)\fC [inline]\fP"
Trigger mouse down event on the element at \fCx\fP and \fCy\fP offset\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.br
\fIxOffset\fP {int} 
.br
\fIyOffset\fP {int} 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - Returns \fCtrue\fP if mouse over was successful, else \fCfalse\fP\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.mouseMove (Object locator, int xOffset, int yOffset)\fC [inline]\fP"
Trigger mouse move event\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.br
\fIxOffset\fP {int} 
.br
\fIyOffset\fP {int} 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - Returns \fCtrue\fP if mouse move is successful, else \fCfalse\fP\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "Object com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.mouseOver (Object locator)\fC [inline]\fP"
Performs a mouse-over operation on the element\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{Object} - Returns a \fBMouse\fP pointer positioning object\&. Returns \fCfalse\fP if mouse-over operation is not successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.mouseUp (Object locator)\fC [inline]\fP"
Trigger mouse up event\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - Returns \fCtrue\fP if mouse up is successful, else false\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.mouseUp (Object locator, int clientX, int clientY)\fC [inline]\fP"
Trigger mouse up event on the element at \fCx\fP and \fCy\fP client positions\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&. 
.br
\fIclientX\fP {int} 
.br
\fIclientY\fP {int} 
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - Returns \fCtrue\fP if mouse over was successful, else \fCfalse\fP\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.scroll (int xVal, int yVal)\fC [inline]\fP"
Scrolls the page by an offset\&.
.PP
\fBParameters:\fP
.RS 4
\fIxVal\fP {int} - Offset along the X-Axis\&. 
.br
\fIyVal\fP {int} - Offset along the Y-Axis\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if scroll operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.
.SS "boolean com\&.zeuslearning\&.automation\&.selenium\&.interactions\&.Mouse\&.scroll (Object locator)\fC [inline]\fP"
Scrolls the page such that the element is now in the view port\&.
.PP
\fBParameters:\fP
.RS 4
\fIlocator\fP {Object} - Path to the element\&.
.RE
.PP
\fBReturns:\fP
.RS 4
{boolean} - returns \fCtrue\fP if scroll operation is successful\&. 
.RE
.PP

.PP
Implements \fBcom\&.zeuslearning\&.automation\&.interactions\&.IMouseOperations\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
