.TH "com.zeuslearning.automation.unittests.testSeleniumGrid" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.unittests.testSeleniumGrid \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbeforeTest\fP (String myBrowser)  throws MalformedURLException "
.br
.ti -1c
.RI "void \fBinitReports\fP (Method method, Object[] arguments)"
.br
.ti -1c
.RI "void \fBtest\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBkill\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "WebDriver \fB_driver\fP = null"
.br
.ti -1c
.RI "\fBMouse\fP \fBm\fP = null"
.br
.ti -1c
.RI "\fBBrowserWindow\fP \fBbrowser\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
