.TH "com.zeuslearning.automation.unittests.JSErrorLogging" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.unittests.JSErrorLogging \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtest\fP ()"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "\fBIDriver\fP \fBiDriver\fP = new \fBDriver\fP('D:/git/automation\-common/src/java/com/zeuslearning/automation/Config\&.properties')"
.br
.ti -1c
.RI "WebDriver \fBdriver\fP = (WebDriver) iDriver\&.getDriver('')"
.br
.ti -1c
.RI "\fBIWindowOperations\fP \fBbrowser\fP = new \fBBrowserWindow\fP(driver)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
