.TH "com.zeuslearning.automation.io.ScreenCapture" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.io.ScreenCapture \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.zeuslearning\&.automation\&.io\&.BasicFileOps\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreenCapture\fP (Object driver)"
.br
.ti -1c
.RI "void \fBgetFullScreenshot\fP (String ScreenshotPath)  throws Exception "
.br
.ti -1c
.RI "void \fBgetScreenshotByElement\fP (Object locator, String ScreenshotPath)  throws Exception "
.br
.ti -1c
.RI "void \fBgetScreenshotByOffset\fP (int xOffset, int yOffset, String ScreenshotPath)  throws Exception "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "File \fBscrFile\fP"
.br
.ti -1c
.RI "WebDriver \fB_driver\fP"
.br
.ti -1c
.RI "\fBQueryHtml\fP \fBquery\fP"
.br
.ti -1c
.RI "int \fBcounter\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
