.TH "com.zeuslearning.automation.selenium.interactions.ExpectedJsConditions" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.selenium.interactions.ExpectedJsConditions \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ExpectedCondition< Boolean > \fBscriptValueMatches\fP (final String str, final String script, final \fBIExecuteJavascript\fP jsExec)"
.br
.ti -1c
.RI "static ExpectedCondition< Boolean > \fBscriptValueChanges\fP (final String str, final String script, final \fBIExecuteJavascript\fP jsExec)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
