.TH "com.zeuslearning.automation.unittests.HTMLRequestFromSelenium" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.unittests.HTMLRequestFromSelenium \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstatusCode\fP"
.br
.ti -1c
.RI "String \fBmethod\fP"
.br
.ti -1c
.RI "String \fBurl\fP"
.br
.ti -1c
.RI "int \fBbytes\fP"
.br
.ti -1c
.RI "String \fBstart\fP"
.br
.ti -1c
.RI "String \fBend\fP"
.br
.ti -1c
.RI "int \fBtimeInMillis\fP"
.br
.ti -1c
.RI "List< ValuePair > \fBrequestHeaders\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
