.TH "com.zeuslearning.automation.unittests.ReadWriteOperations" 3 "Fri Mar 9 2018" "Automation Common" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.zeuslearning.automation.unittests.ReadWriteOperations \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestWriteFunction\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBlockWrite\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBtestReadFunction\fP ()  throws Exception "
.br
.ti -1c
.RI "void \fBreadPdfFile\fP ()  throws Exception "
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "\fBIDriver\fP \fBiDriver\fP = new \fBDriver\fP('/src/java/com/zeuslearning/automation/Config\&.properties')"
.br
.ti -1c
.RI "Object \fBdriver\fP = iDriver\&.getDriver('')"
.br
.ti -1c
.RI "\fBIWindowOperations\fP \fBbrowser\fP = new \fBBrowserWindow\fP(driver)"
.br
.ti -1c
.RI "String \fBdata\fP = 'This is the data to be added\&.'"
.br
.ti -1c
.RI "String \fBfilePath\fP = 'C:\\\\Users\\\\admin\\\\git\\\\automation\-common\\\\resources\\\\IO documents\\\\testFile\&.txt'"
.br
.ti -1c
.RI "String \fBpdfUrl\fP = 'file:///C:/Users/admin/Downloads/dotnet_TheRaceforEmpires\&.pdf'"
.br
.ti -1c
.RI "\fBTextFileOps\fP \fBwriteOps\fP = new \fBTextFileOps\fP(driver)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Automation Common from the source code\&.
